version: '3.8'

services:
  server:
    image: github.com/rohit21755/go_webrtc
    deploy:
      replicas: 1
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-size: "200m"
        max-file: "10"
    ports:
      -8080:8080
    command: -addr :8000